import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="icon" href="/favicon.ico" />
          <title>{metadata.title}</title>
        </head>
        <body className={`${inter.className} bg-gray-100`}>
          <div className="min-h-screen flex flex-col">
            <header className="bg-customRed text-white py-4">
              <div className="container mx-auto px-4">
                <h1 className="text-3xl text-center font-bold">MANAN A TECHNO SURGE</h1>
              </div>
            </header>
            <main className="flex-grow container mx-auto px-4 py-6 bg-white shadow-md rounded-lg">
              {children}
            </main>
            <footer className="bg-customRed text-white py-4">
              <div className="container mx-auto px-4 text-center">
                <p>© {new Date().getFullYear()} MANAN A TECHNO SURGE. All rights reserved.</p>
              </div>
            </footer>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
